// examples/tanstack-query-svelte-spa/src/routes/ArchivedTodo/ArchivedTodoCard.svelte
<script lang="ts">
  import type { ArchivedTodo } from 'src/core/domain/archivedTodo/entities/ArchivedTodo';
  import { archivedTodoService } from 'src/core/infrastructure/services/ArchivedTodoService';
  import { formatDate } from 'src/utils/formatDate';

  let { todo }: { todo: ArchivedTodo } = $props();

  const unarchiveOne = archivedTodoService.unarchiveOne.useHook();
  const deleteOne = archivedTodoService.deleteOne.useHook();

  let menuOpen = $state(false);

  function handleClickOutside(e: MouseEvent) {
    const target = e.target as HTMLElement;
    if (!target.closest('.menu-wrapper')) {
      menuOpen = false;
    }
  }

  $effect(() => {
    if (menuOpen) {
      document.addEventListener('mousedown', handleClickOutside);
      return () => document.removeEventListener('mousedown', handleClickOutside);
    }
  });
</script>

<div class="archived-card">
  <div class="archived-card-info">
    {#if deleteOne.isPending || unarchiveOne.isPending}
      <div class="loader loader-sm"></div>
    {/if}
    <h4>{todo.title}</h4>
    <span class="text-sm">Completed At: {formatDate(todo.completedAt)}</span>
    <span class="text-sm">Archived At: {formatDate(todo.archivedAt)}</span>
  </div>
  <div class="menu-wrapper">
    <button
      type="button"
      class="menu-trigger"
      onclick={() => (menuOpen = !menuOpen)}
    >
      <svg width="16" height="16" viewBox="0 0 16 16" fill="currentColor">
        <circle cx="3" cy="8" r="1.5" />
        <circle cx="8" cy="8" r="1.5" />
        <circle cx="13" cy="8" r="1.5" />
      </svg>
    </button>
    {#if menuOpen}
      <div class="menu-dropdown">
        <div class="menu-label">Archived Todo Options</div>
        <button
          type="button"
          class="menu-item"
          onclick={() => {
            unarchiveOne.invoke({ id: todo.id });
            menuOpen = false;
          }}
        >
          Unarchive
        </button>
        <button
          type="button"
          class="menu-item danger"
          onclick={() => {
            deleteOne.invoke({ id: todo.id });
            menuOpen = false;
          }}
        >
          Delete
        </button>
      </div>
    {/if}
  </div>
</div>

// examples/tanstack-query-nextjs-ioc/src/app/archived/ArchivedTodoCard.tsx
'use client';

import { useState, useEffect, useRef } from 'react';
import { formatDate } from '@/utils/formatDate';
import { IconDots, IconRestore, IconTrash } from '@/components/icons';
import { getContainer } from '@/core/global/container';
import { ArchivedTodo } from '@/core/domain/archivedTodo/entities/ArchivedTodo';

type Props = {
  archivedTodo: ArchivedTodo;
};

export const ArchivedTodoCard = ({ archivedTodo }: Props) => {
  const { archivedTodoService } = getContainer();

  const unarchiveOne = archivedTodoService.unarchiveOne.useHook();
  const deleteOne = archivedTodoService.deleteOne.useHook();
  const [menuOpen, setMenuOpen] = useState(false);
  const menuRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!menuOpen) return;
    const handleClick = (e: MouseEvent) => {
      if (menuRef.current && !menuRef.current.contains(e.target as Node)) {
        setMenuOpen(false);
      }
    };
    document.addEventListener('mousedown', handleClick);
    return () => document.removeEventListener('mousedown', handleClick);
  }, [menuOpen]);

  return (
    <div className="archived-card">
      <div className="archived-card-info">
        {(deleteOne.isPending || unarchiveOne.isPending) && (
          <div className="loader loader-sm" />
        )}
        <h4>{archivedTodo.title}</h4>
        <span className="text-sm">{`Completed At: ${formatDate(archivedTodo.completedAt)}`}</span>
        <span className="text-sm">{`Archived At: ${formatDate(archivedTodo.archivedAt)}`}</span>
      </div>
      <div className="menu-wrapper" ref={menuRef}>
        <button
          type="button"
          className="menu-trigger"
          onClick={() => setMenuOpen((o) => !o)}
        >
          <IconDots />
        </button>
        {menuOpen && (
          <div className="menu-dropdown">
            <div className="menu-label">Archived Todo Options</div>
            <button
              type="button"
              className="menu-item"
              onClick={() => {
                unarchiveOne.invoke({ id: archivedTodo.id });
                setMenuOpen(false);
              }}
            >
              <IconRestore /> Unarchive
            </button>
            <button
              type="button"
              className="menu-item danger"
              onClick={() => {
                deleteOne.invoke({ id: archivedTodo.id });
                setMenuOpen(false);
              }}
            >
              <IconTrash size="0.875rem" /> Delete
            </button>
          </div>
        )}
      </div>
    </div>
  );
};
