// examples/tanstack-query-nextjs-ioc/src/app/archived/ArchivedTodoList.tsx
'use client';

import { getContainer } from '@/core/global/container';
import { ArchivedTodoCard } from './ArchivedTodoCard';
import { mapArchivedTodoDtoToArchivedTodo } from '@/core/domain/archivedTodo/entities/ArchivedTodo';

export const ArchivedTodoList = () => {
  const { archivedTodoService } = getContainer();
  const { data, hasNextPage, isFetchingNextPage, fetchNextPage } =
    archivedTodoService.getAll.useSuspenseHook();

  const archivedTodos = data.pages.flatMap((page) =>
    page.list.map(mapArchivedTodoDtoToArchivedTodo),
  );

  return (
    <div className="scroll-area">
      {archivedTodos.map((archivedTodo) => (
        <ArchivedTodoCard
          key={archivedTodo.id}
          archivedTodo={archivedTodo}
        />
      ))}
      {hasNextPage && (
        <div className="flex-center">
          <button
            type="button"
            className="btn btn-light"
            onClick={() => fetchNextPage()}
            disabled={isFetchingNextPage}
          >
            {isFetchingNextPage ? (
              <span className="loader loader-sm" />
            ) : (
              'Load More'
            )}
          </button>
        </div>
      )}
    </div>
  );
};

// examples/tanstack-query-svelte-spa/src/routes/ArchivedTodo/ArchivedTodoList.svelte
<script lang="ts">
  import { archivedTodoService } from 'src/core/infrastructure/services/ArchivedTodoService';
  import { mapArchivedTodoDtoToArchivedTodo } from 'src/core/domain/archivedTodo/entities/ArchivedTodo';
  import ArchivedTodoCard from './ArchivedTodoCard.svelte';

  const query = archivedTodoService.getAll.useHook();

  const archivedTodos = $derived(
    query.data?.pages.flatMap((page) =>
      page.list.map(mapArchivedTodoDtoToArchivedTodo),
    ) ?? [],
  );
</script>

{#if query.isPending}
  <div class="loader-container">
    <div class="loader"></div>
  </div>
{:else if query.isError}
  <p>Error loading archived todos</p>
{:else}
  <div class="scroll-area">
    {#each archivedTodos as todo (todo.id)}
      <ArchivedTodoCard {todo} />
    {/each}
    {#if archivedTodos.length === 0}
      <p style="color: var(--text-dimmed); text-align: center; padding: 2rem;">
        No archived todos yet. Archive completed todos from the Active Todos page.
      </p>
    {/if}
    {#if query.hasNextPage}
      <div class="flex-center">
        <button
          type="button"
          class="btn btn-light"
          onclick={() => query.fetchNextPage()}
          disabled={query.isFetchingNextPage}
        >
          {#if query.isFetchingNextPage}
            <span class="loader loader-sm"></span>
          {:else}
            Load More
          {/if}
        </button>
      </div>
    {/if}
  </div>
{/if}
