// examples/tanstack-query-svelte-spa/src/routes/ActiveTodo/ActiveTodoList.svelte
<script lang="ts">
  import { activeTodoService } from 'src/core/infrastructure/services/ActiveTodoService';
  import ActiveTodoCard from './ActiveTodoCard.svelte';

  const query = activeTodoService.getAll.useHook();
</script>

{#if query.isPending}
  <div class="loader-container">
    <div class="loader"></div>
  </div>
{:else if query.isError}
  <p>Error loading todos</p>
{:else if query.data}
  <div class="scroll-area">
    {#each query.data as todo (todo.id)}
      <ActiveTodoCard {todo} />
    {/each}
    {#if query.data.length === 0}
      <p style="color: var(--text-dimmed); text-align: center; padding: 2rem;">
        No active todos. Add one above!
      </p>
    {/if}
  </div>
{/if}

// examples/rtk-spa/src/routes/ActiveTodo/ActiveTodoList.tsx
import { ActiveTodoCard } from './ActiveTodoCard';
import { activeTodoService } from 'src/core/infrastructure/services/ActiveTodoService';
import { useAppSelector } from 'src/lib/store';
import { useMemo } from 'react';

export const ActiveTodoList = () => {
  const { data, isPending } = activeTodoService.getAll.useHook();
  const priorityDict = useAppSelector(
    (state) => state.todo.priorityTodo.dict,
  );

  const sortedData = useMemo(() => {
    if (!data) return [];
    return [...data].sort((a, b) => {
      const aPrioritized = priorityDict[a.id]?.isPrioritized ?? false;
      const bPrioritized = priorityDict[b.id]?.isPrioritized ?? false;
      if (aPrioritized && !bPrioritized) return -1;
      if (!aPrioritized && bPrioritized) return 1;
      return 0;
    });
  }, [data, priorityDict]);

  if (isPending || !data) {
    return (
      <div className="loader-container">
        <div className="loader" />
      </div>
    );
  }

  return (
    <div className="scroll-area">
      {sortedData.map((todo) => (
        <ActiveTodoCard key={todo.id} todo={todo} />
      ))}
    </div>
  );
};
