// examples/tanstack-query-svelte-spa/src/App.svelte
<script lang="ts">
  import { QueryClientProvider } from '@tanstack/svelte-query';
  import { queryClient } from 'src/core/global/queryClient';
  import ActiveTodo from './routes/ActiveTodo/ActiveTodo.svelte';
  import ArchivedTodo from './routes/ArchivedTodo/ArchivedTodo.svelte';
  import Review from './routes/Review/Review.svelte';

  type Route = 'active' | 'archived' | 'review';

  let currentRoute = $state<Route>('active');

  const navigate = (route: Route) => {
    currentRoute = route;
  };
</script>

<QueryClientProvider client={queryClient}>
  <div class="app-layout">
    <header class="app-header">
      <span>Chimeric Svelte Todo</span>
    </header>

    <nav class="app-nav">
      <a
        href="#active"
        class="nav-link {currentRoute === 'active' ? 'active' : ''}"
        onclick={(e) => { e.preventDefault(); navigate('active'); }}
      >
        Active Todos
      </a>
      <a
        href="#archived"
        class="nav-link {currentRoute === 'archived' ? 'active' : ''}"
        onclick={(e) => { e.preventDefault(); navigate('archived'); }}
      >
        Archived Todos
      </a>
      <a
        href="#review"
        class="nav-link {currentRoute === 'review' ? 'active' : ''}"
        onclick={(e) => { e.preventDefault(); navigate('review'); }}
      >
        Review Todos
      </a>
    </nav>

    <main class="app-main">
      {#if currentRoute === 'active'}
        <ActiveTodo />
      {:else if currentRoute === 'archived'}
        <ArchivedTodo />
      {:else if currentRoute === 'review'}
        <Review />
      {/if}
    </main>
  </div>
</QueryClientProvider>

// examples/tanstack-query-vue-spa/src/App.vue
<template>
  <div class="app-layout">
    <header class="app-header">
      <div class="avatar">C</div>
    </header>

    <nav class="app-nav">
      <RouterLink to="/" class="nav-link" :class="{ active: isActive('/') }">
        Active Todos
      </RouterLink>
      <RouterLink
        to="/archived"
        class="nav-link"
        :class="{ active: isActive('/archived') }"
      >
        Archived Todos
      </RouterLink>
      <RouterLink
        to="/review"
        class="nav-link"
        :class="{ active: isActive('/review') }"
      >
        Review Todos
      </RouterLink>
    </nav>

    <main class="app-main">
      <RouterView />
    </main>
  </div>
</template>

<script setup lang="ts">
import { useRoute } from 'vue-router';

const route = useRoute();

const isActive = (path: string): boolean => {
  if (path === '/') return route.path === '/';
  return route.path.startsWith(path);
};
</script>
