// examples/tanstack-query-svelte-spa/src/routes/ActiveTodo/AddNewActiveTodoForm.svelte
<script lang="ts">
  import { activeTodoService } from 'src/core/infrastructure/services/ActiveTodoService';

  let title = $state('');
  let isSubmitting = $state(false);
  const createOne = activeTodoService.createOne.useHook();

  async function handleSubmit(e: SubmitEvent) {
    e.preventDefault();
    if (!title.trim()) return;
    isSubmitting = true;
    try {
      await createOne.invoke({ title: title.trim() });
      title = '';
    } finally {
      isSubmitting = false;
    }
  }
</script>

<form class="form-row" onsubmit={handleSubmit}>
  <input
    class="text-input"
    type="text"
    placeholder="Enter your todo"
    bind:value={title}
    disabled={isSubmitting}
  />
  <button class="btn" type="submit" disabled={isSubmitting || !title.trim()}>
    {#if isSubmitting}
      <span class="loader loader-sm"></span>
    {:else}
      Add
    {/if}
  </button>
</form>

// examples/tanstack-query-nextjs-ioc/src/app/active-todo/AddNewActiveTodoForm.tsx
'use client';

import { useState } from 'react';
import { getContainer } from '@/core/global/container';

export const AddNewActiveTodoForm = () => {
  const { activeTodoService } = getContainer();
  const { invoke, isPending } = activeTodoService.createOne.useHook();
  const [title, setTitle] = useState('');
  const [error, setError] = useState('');

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (title.length < 1) {
      setError('Must be at least 1 character long');
      return;
    }
    setError('');
    await invoke({ title });
    setTitle('');
  };

  return (
    <form onSubmit={handleSubmit}>
      <div className="form-row">
        <div>
          <input
            type="text"
            className={`text-input ${error ? 'error' : ''}`}
            placeholder="Enter your todo"
            value={title}
            onChange={(e) => {
              setTitle(e.target.value);
              if (error) setError('');
            }}
          />
          {error && <div className="input-error">{error}</div>}
        </div>
        <button className="btn" type="submit" disabled={isPending}>
          {isPending ? <span className="loader loader-sm" /> : 'Add'}
        </button>
      </div>
    </form>
  );
};
