// examples/tanstack-query-spa/src/routes/ActiveTodo/ActiveTodoList.tsx
import { Flex, Loader, ScrollArea } from '@mantine/core';
import { useViewportSize } from '@mantine/hooks';
import { ActiveTodoCard } from './ActiveTodoCard';
import { activeTodoService } from 'src/core/infrastructure/services/ActiveTodoService';

export const ActiveTodoList = () => {
  const { data, isPending } = activeTodoService.getAll.useHook();
  const { height } = useViewportSize();

  if (isPending || !data) {
    return (
      <Flex justify="center" align="center" w="100%" h="100%">
        <Loader />
      </Flex>
    );
  }

  return (
    <ScrollArea.Autosize mah={`calc(${height}px - 172px`}>
      {data.map((todo) => (
        <ActiveTodoCard key={todo.id} todo={todo} />
      ))}
    </ScrollArea.Autosize>
  );
};

// examples/tanstack-query-svelte-spa/src/routes/ActiveTodo/ActiveTodoList.svelte
<script lang="ts">
  import { activeTodoService } from 'src/core/infrastructure/services/ActiveTodoService';
  import ActiveTodoCard from './ActiveTodoCard.svelte';

  const query = activeTodoService.getAll.useHook();
</script>

{#if query.isPending}
  <div class="loader-container">
    <div class="loader"></div>
  </div>
{:else if query.isError}
  <p>Error loading todos</p>
{:else if query.data}
  <div class="scroll-area">
    {#each query.data as todo (todo.id)}
      <ActiveTodoCard {todo} />
    {/each}
    {#if query.data.length === 0}
      <p style="color: var(--text-dimmed); text-align: center; padding: 2rem;">
        No active todos. Add one above!
      </p>
    {/if}
  </div>
{/if}
