// examples/basic-todo-app/src/routes/ActiveTodo/AddNewActiveTodoForm.tsx
import { Button, Group, TextInput } from '@mantine/core';
import { hasLength, useForm } from '@mantine/form';
import { activeTodoService } from 'src/core/infrastructure/services/ActiveTodoService';

export const AddNewActiveTodoForm = () => {
  const { invoke, isPending } = activeTodoService.createOne.use();
  const form = useForm({
    mode: 'uncontrolled',
    initialValues: {
      title: '',
    },
    validate: {
      title: hasLength({ min: 1 }, 'Must be at least 1 character long'),
    },
  });

  return (
    <form
      onSubmit={form.onSubmit(async (values) => {
        await invoke({ title: values.title });
        form.setFieldValue('title', '');
      })}
    >
      <Group justify="space-between" align="start" h="100%" mt="md">
        <TextInput
          key={form.key('title')}
          placeholder="Enter your todo"
          {...form.getInputProps('title')}
        />
        <Button type="submit" loading={isPending} disabled={isPending}>
          Add
        </Button>
      </Group>
    </form>
  );
};

// examples/tanstack-query-svelte-spa/src/routes/ActiveTodo/AddNewActiveTodoForm.svelte
<script lang="ts">
  import { activeTodoService } from 'src/core/infrastructure/services/ActiveTodoService';

  let title = $state('');
  let isSubmitting = $state(false);
  const createOne = activeTodoService.createOne.useHook();

  async function handleSubmit(e: SubmitEvent) {
    e.preventDefault();
    if (!title.trim()) return;
    isSubmitting = true;
    try {
      await createOne.invoke({ title: title.trim() });
      title = '';
    } finally {
      isSubmitting = false;
    }
  }
</script>

<form class="form-row" onsubmit={handleSubmit}>
  <input
    class="text-input"
    type="text"
    placeholder="Enter your todo"
    bind:value={title}
    disabled={isSubmitting}
  />
  <button class="btn" type="submit" disabled={isSubmitting || !title.trim()}>
    {#if isSubmitting}
      <span class="loader loader-sm"></span>
    {:else}
      Add
    {/if}
  </button>
</form>
