// examples/tanstack-query-svelte-spa/src/routes/ActiveTodo/ActiveTodoCard.svelte
<script lang="ts">
  import type { ActiveTodo } from 'src/core/domain/activeTodo/entities/ActiveTodo';
  import { activeTodoService } from 'src/core/infrastructure/services/ActiveTodoService';
  import { formatDate } from 'src/utils/formatDate';

  let { todo }: { todo: ActiveTodo } = $props();

  const completeOne = activeTodoService.completeOne.useHook();
  const uncompleteOne = activeTodoService.uncompleteOne.useHook();
  const deleteOne = activeTodoService.deleteOne.useHook();

  const isLoading = $derived(
    deleteOne.isPending || completeOne.isPending || uncompleteOne.isPending,
  );

  function handleToggle() {
    if (deleteOne.isPending) return;
    if (todo.completedAt) {
      uncompleteOne.invoke({ id: todo.id });
    } else {
      completeOne.invoke({ id: todo.id });
    }
  }
</script>

<div class="todo-card">
  <div
    class="checkbox-card {todo.completedAt ? 'checked' : ''} {deleteOne.isPending ? 'disabled' : ''}"
    role="checkbox"
    aria-checked={!!todo.completedAt}
    tabindex="0"
    onclick={handleToggle}
    onkeydown={(e) => e.key === 'Enter' && handleToggle()}
  >
    {#if isLoading}
      <div class="loader loader-sm" style="margin: 0.25rem;"></div>
    {:else}
      <div class="checkbox-indicator {todo.completedAt ? 'checked' : ''}"></div>
    {/if}
    <div class="todo-info">
      <h4>{todo.title}</h4>
      <span class="text-sm">Created: {formatDate(todo.createdAt)}</span>
      {#if todo.completedAt}
        <span class="text-sm">Completed: {formatDate(todo.completedAt)}</span>
      {/if}
    </div>
  </div>
  <button
    type="button"
    class="icon-btn danger"
    onclick={() => deleteOne.invoke({ id: todo.id })}
    disabled={deleteOne.isPending}
    aria-label="Delete todo"
  >
    <svg width="16" height="16" viewBox="0 0 16 16" fill="currentColor">
      <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5ZM11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1H11Zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5h9.916Z"/>
    </svg>
  </button>
</div>

// examples/basic-todo-app/src/routes/ActiveTodo/ActiveTodoCard.tsx
import {
  Box,
  Checkbox,
  Group,
  Loader,
  Menu,
  Stack,
  Text,
  Title,
  rem,
} from '@mantine/core';
import { format } from 'date-fns';
import {
  IconDots,
  IconPlus,
  IconStar,
  IconStarFilled,
  IconTrash,
} from '@tabler/icons-react';
import { ActiveTodo } from 'src/core/domain/activeTodo/entities/ActiveTodo';
import { activeTodoService } from 'src/core/infrastructure/services/ActiveTodoService';
import { savedForLaterTodoService } from 'src/core/infrastructure/services/SavedForLaterTodoService';

type OwnProps = {
  todo: ActiveTodo;
};

export const ActiveTodoCard = ({ todo }: OwnProps) => {
  const saveForLater = savedForLaterTodoService.saveForLater.useHook();
  const completeOne = activeTodoService.completeOne.useHook();
  const uncompleteOne = activeTodoService.uncompleteOne.useHook();
  const deleteOne = activeTodoService.deleteOne.useHook();
  const prioritize = activeTodoService.prioritize;
  const deprioritize = activeTodoService.deprioritize;

  return (
    <Box key={todo.id} p="xs" pr="lg">
      <Group wrap="nowrap" align="flex-start">
        <Checkbox.Card
          radius="md"
          checked={Boolean(todo.completedAt)}
          disabled={deleteOne.isPending}
          onClick={() => {
            const isCompleted = Boolean(todo.completedAt);
            if (isCompleted) {
              uncompleteOne.invoke({ id: todo.id });
            } else {
              completeOne.invoke({ id: todo.id });
            }
          }}
        >
          <Group wrap="nowrap" align="flex-start">
            {deleteOne.isPending ||
            completeOne.isPending ||
            uncompleteOne.isPending ? (
              <Loader p="xs" />
            ) : (
              <Checkbox.Indicator mt="sm" ml="sm" />
            )}
            <Stack p="xs" align="stretch" gap="xs">
              <Title order={4}>{todo.title}</Title>
              <Text size="sm">{`Created At: ${format(todo.createdAt, 'M/d/yyyy h:m aaa')}`}</Text>
              <Text size="sm">{`Completed At: ${todo.completedAt ? format(todo.completedAt, 'M/d/yyyy h:m aaa') : 'N/A'}`}</Text>
            </Stack>
            {todo.isPrioritized && (
              <Box style={{ flexGrow: 1 }} p="xs">
                <IconStarFilled
                  style={{
                    width: rem(20),
                    height: rem(20),
                    position: 'absolute',
                    right: rem(70),
                  }}
                />
              </Box>
            )}
          </Group>
        </Checkbox.Card>
        <Menu shadow="md" width={200}>
          <Menu.Target>
            <IconDots />
          </Menu.Target>

          <Menu.Dropdown>
            <Menu.Label>Todo Options</Menu.Label>
            <Menu.Item
              color="red"
              leftSection={
                <IconTrash style={{ width: rem(14), height: rem(14) }} />
              }
              onClick={() => deleteOne.invoke({ id: todo.id })}
            >
              Delete
            </Menu.Item>
            {todo.isPrioritized ? (
              <Menu.Item
                leftSection={
                  <IconStar style={{ width: rem(14), height: rem(14) }} />
                }
                onClick={() => deprioritize({ id: todo.id })}
              >
                Deprioritize
              </Menu.Item>
            ) : (
              <Menu.Item
                leftSection={
                  <IconStarFilled style={{ width: rem(14), height: rem(14) }} />
                }
                onClick={() => prioritize({ id: todo.id })}
              >
                Prioritize
              </Menu.Item>
            )}
            <Menu.Item
              leftSection={
                <IconPlus style={{ width: rem(14), height: rem(14) }} />
              }
              onClick={() =>
                saveForLater.invoke({
                  activeTodoId: todo.id,
                })
              }
            >
              Save For Later
            </Menu.Item>
          </Menu.Dropdown>
        </Menu>
      </Group>
    </Box>
  );
};
